from typing import Optional

from loguru import logger

from pixelle_video.models.media import MediaResult
from pixelle_video.services.image_backends.base import ImageBackend


class ComfyUIBackend(ImageBackend):
    """ComfyUI-based image generation backend"""

    def __init__(self, media_service, config: dict):
        """
        Args:
            media_service: MediaService instance (for accessing core ComfyKit)
            config: Image-specific config dict
        """
        self._media_service = media_service
        self._config = config

    async def generate(
        self,
        prompt: str,
        width: Optional[int] = None,
        height: Optional[int] = None,
        **params,
    ) -> MediaResult:
        """Generate image using ComfyUI workflow"""
        workflow = params.get("workflow")
        workflow_info = self._media_service._resolve_workflow(workflow=workflow)

        workflow_params = {"prompt": prompt}
        if width is not None:
            workflow_params["width"] = width
        if height is not None:
            workflow_params["height"] = height
        for key in ("negative_prompt", "steps", "seed", "cfg", "sampler"):
            if key in params and params[key] is not None:
                workflow_params[key] = params[key]
        workflow_params.update(
            {k: v for k, v in params.items() if k not in ("workflow", "negative_prompt", "steps", "seed", "cfg", "sampler")}
        )

        logger.debug(f"ComfyUI backend parameters: {workflow_params}")

        kit = await self._media_service.core._get_or_create_comfykit()

        if workflow_info["source"] == "runninghub" and "workflow_id" in workflow_info:
            workflow_input = workflow_info["workflow_id"]
            logger.info(f"Executing RunningHub workflow: {workflow_input}")
        else:
            workflow_input = workflow_info["path"]
            logger.info(f"Executing selfhost workflow: {workflow_input}")

        result = await kit.execute(workflow_input, workflow_params)

        if result.status != "completed":
            error_msg = result.msg or "Unknown error"
            logger.error(f"ComfyUI image generation failed: {error_msg}")
            raise Exception(f"ComfyUI image generation failed: {error_msg}")

        if not result.images:
            raise Exception("No image generated by ComfyUI workflow")

        image_url = result.images[0]
        logger.info(f"ComfyUI generated image: {image_url}")

        return MediaResult(media_type="image", url=image_url)
